version : '3'

services :
        voip:
                build: .
                image: he201573/voip
                container_name: voip
                ports:
                        - "5060:5060/udp"
                        - "16384:16384/udp"
                        - "16385:16385/udp"
                        - "16386:16386/udp"
                        - "16387:16387/udp"
                        - "16388:16388/udp"
                        - "16389:16389/udp"
                        - "16390:16390/udp"
                        - "16391:16391/udp"
                        - "16392:16392/udp"
                        - "16393:16393/udp"
                        - "16394:16394/udp"
                restart: always
