version: '2'
services:
  rainloop:
    image: hardware/rainloop
    depends_on:
      - mail
    volumes:
      -  ./data/rainloop:/rainloop/data

  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: woodytoys1-1.be
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./data/mail/data:/var/mail
      - ./data/mail/state:/var/mail-state
      - ./config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
      - ENABLE_SPAMASSASSIN= 1
      - ENABLE_CLAMAV= 1
      - ENABLE_FAIL2BAN= 1
      - ENABLE_POSTGREY= 1
      - ONE_DIR= 1
      - DMS_DEBUG= 0
      - SSL_TYPE= letsencrypt
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  entry:
    image: abiosoft/caddy:latest
    restart: always
    privileged: true
    links:
      - rainloop
    ports:
      - "80:80"
      - "443:443"
    volumes:
      -  ./Caddyfile:/etc/Caddyfile
      -  ./data/entry:/root/.caddy
